name: Jira

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - uses: procyon-creative/jira-action-man@main
        id: jira
        with:
          projects: "PTL"
          from: "branch,title,commits,body"
          post_to_jira: true
          jira_comment_mode: update
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          jira_email: ${{ secrets.JIRA_EMAIL }}
          jira_api_token: ${{ secrets.JIRA_API_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.jira.outputs.found == 'true'
        run: echo "Linked Jira issues - ${{ steps.jira.outputs.keys }}"
